### ISSUE TITLE
Need help to custom it

### ISSUE THREAD

**Issue by 4dvn** [zukaitis/midi-grid#3]
I have a 16 buttons midi from avr project and i wanna switch it to stm32, can you give me some example code of it with rgb?

**Comment by zukaitis** [comment]
Hey, all the hardware configuration (GPIO, PWM, DMA) is set up in [GridDriver.cpp](https://github.com/zukaitis/midi-grid/blob/master/Firmware/src/hardware/grid/GridDriver.cpp) file. Since you only need 16 buttons, you could get away with using as little as 3 PWM GPIO outputs (instead of 12 used in my circuit), but that depends on the way you want to connect them, check the [schematics](https://github.com/zukaitis/midi-grid/blob/master/Hardware/midi_grid.pdf) for reference. Hope that helps, have fun with your project!
